# Generated by Django 2.2.28 on 2024-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_paymentmode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20),
        ),
    ]
