# Generated by Django 2.2.28 on 2024-07-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_details', '0002_auto_20240707_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_staff',
            field=models.CharField(default='self', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phno',
            field=models.IntegerField(),
        ),
    ]
