# Generated by Django 2.2.28 on 2024-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_details', '0003_auto_20240710_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
