# Generated by Django 2.2.28 on 2024-07-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
